"""Render the existing public inventory; never rewrite its downloadable bytes.

Build-time only. Uses the already installed markdown-it-py renderer, not browser
JavaScript. Raw HTML is disabled; license fences retain their exact text.
"""
import argparse
import hashlib
import html
from pathlib import Path
import re

from markdown_it import MarkdownIt

ROOT = Path(__file__).resolve().parents[1]
START = '    <!-- generated-notices:start -->'
END = '    <!-- generated-notices:end -->'


def render(source: str) -> str:
    # The page already has its title. The generator comment is not license prose.
    source = re.sub(r'^# Third-party software notices\r?\n', '', source, count=1)
    source = re.sub(r'^<!-- Generated by [^\n]+ -->\r?\n', '', source, flags=re.M)
    md = MarkdownIt('commonmark', {'html': False}).enable('table')

    def heading(tokens, index, options, env):
        title = tokens[index + 1].content
        anchor = re.sub(r'[^a-z0-9]+', '-', title.lower()).strip('-')
        tokens[index].attrSet('id', anchor)
        return md.renderer.renderToken(tokens, index, options, env)

    def fence(tokens, index, options, env):
        text = tokens[index].content
        # Preserve trailing source whitespace in the DOM without dirty HTML lines.
        escaped = re.sub(r'[ \t]+(?=\n)', lambda m: ''.join('&#32;' if c == ' ' else '&#9;' for c in m[0]), html.escape(text))
        return ('<details class="license-text"><summary>Read license text</summary>\n'
                '<pre tabindex="0" aria-label="License text"><code>' + escaped + '</code></pre>\n</details>\n')

    md.renderer.rules['heading_open'] = heading
    md.renderer.rules['fence'] = fence
    result = md.render(source)
    result = result.replace('<table>', '<div class="notice-table" tabindex="0" role="region" aria-label="Package inventory table"><table>')
    return result.replace('</table>', '</table></div>')


def page_content(page: str, source: bytes) -> str:
    rendered = render(source.decode('utf-8'))
    fragment = (START + '\n    <!-- Inventory SHA-256: ' + hashlib.sha256(source).hexdigest() + ' -->\n'
                '    <nav class="notice-contents" aria-label="On this page">\n'
                '      <a href="#generation-summary">Generation summary</a>\n'
                '      <a href="#release-review-required">Release review required</a>\n'
                '      <a href="#package-inventory">Package inventory</a>\n'
                '      <a href="#bundled-notice-texts">License texts</a>\n'
                '    </nav>\n    <article class="notice-inventory" aria-label="Generated notice inventory">\n'
                + rendered + '    </article>\n' + END)
    if START in page:
        before, remaining = page.split(START, 1)
        _, after = remaining.split(END, 1)
        return before + fragment + after
    old = '    <iframe class="notice-frame" title="Third-party software notices" src="./THIRD_PARTY_NOTICES.txt"></iframe>'
    if page.count(old) != 1:
        raise ValueError('Expected exactly one legacy inventory frame or generated region')
    return page.replace(old, fragment)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = (ROOT / 'licenses/THIRD_PARTY_NOTICES.txt').read_bytes()
    target = ROOT / 'licenses/index.html'
    current = target.read_text()
    generated = page_content(current, source)
    if args.check:
        if generated != current:
            raise SystemExit('Rendered inventory is stale. Run scripts/render_notices.py.')
    else:
        target.write_text(generated)
    print('Notice page matches the unchanged downloadable inventory.')


if __name__ == '__main__':
    main()
